---
title: "Econ 204: HW 3"
author: "Jenna Anderson, Sydney Mayes"
date: "2023-05-15"
output:  
  html_document:
    theme: simplex
    code_folding: hide
---

```{r setup,  include = TRUE, echo=TRUE, warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE, results = FALSE)
library(tidyverse)
library(here)
library(janitor)
library(equatiomatic)
```

```{r}
# Cleaning and tidying data
ca_ev <- read_csv(here('HW3_data.csv')) %>% 
  clean_names()
long_ca_ev <- pivot_longer(ca_ev, cols = q_dac:q_non_dac, names_to = 'location', values_to = 'quantity')
```

1.
```{r}
# Run linear regressions
dac_model <- lm(price_dollars ~ quantity, data = filter(long_ca_ev, location == 'q_dac'))
dac_model$coefficients

non_dac_model <- lm(price_dollars ~ quantity, data = filter(long_ca_ev, location == 'q_non_dac'))
non_dac_model$coefficients

# Plot the data
ggplot(data = long_ca_ev, aes(x = quantity, y = price_dollars, col = location)) +
  geom_point() +
  geom_abline(slope = -6.611437, intercept = 116854.835741) +
  geom_abline(slope = -2.730926, intercept = 158034.280239) +
  #geom_abline(slope = -4.652827, intercept = 351488.7) +
  scale_color_viridis_d() +
  labs(x = 'Number of EVs', y = 'Price of EV' ) +
  theme_bw()

# When we visualize the data, it appears that non-DAC groups demand more EVs at every price point than do non-DAC groups. This may be because non-DAC groups have higher incomes than DAC groups. DAC groups have a much lower willingness to pay than non-DAC groups. An interesting thing to note is that the DAC groups seem to have a more inelastic demand curve than non-DAC groups. This means that with a price increase, non-DAC groups will demand fewer EVs, whereas this effect is not as strong with DAC groups; they will demand fewer EVs with a price increase but not by as large a degree as DAC groups. It is possible that non-DAC groups can afford to wait and see whether the prices drop again in the future whereas DAC groups feel like if they have the opportunity, it is better to not hesitate and purchase an EV in case their financial situation changes in the future.
```
2. 18,900 dollars per EV
```{r}
# Marginal externaliity cost is 63 kg * 300 dollars = 18,900 dollars per EV
```

3.
```{r}
#3. What is the aggregate annual demand curve for EVs? What is the supply curve for EVs? What is the “benefit” to consumers under the status quo? What is the “benefit” to producers under the status quo? What is the environmental cost under the status quo?

# p = -6.611437q + 116854.835741 (dac)
# 6.611437q = 116854.835741 - p
# q = 116854.835741/6.611437 - p/6.611437
# q = 17674.65 - 0.151253*p (dac)


# p = -2.730926q + 158034.280239
# 2.730926q = 158034.280239 - p 
# q = 158034.280239/2.730926 - p/2.730926
# q = 57868.39 - 0.3661762*p (non_dac)


# q = 17674.65 - 0.151253*p (dac)
# q = 57868.39 - 0.3661762*p (non_dac)
# q = 75543.04 - 0.5174292*p (agg)
# 0.5174292*p = 75543.04 - q
# p = 75543.04/0.5174292 - q/0.5174292
# p = 145996.9 - 1.932632*q (agg)


# Aggregate annual demand curve is p = 145996.9 - 1.932632*q
# Slope of supply curve = 50000/49671.59 = 1.006612
# Supply curve for EVs is P = 1.006612*Q
# 1.006612*q = 145996.9 - 1.932632*q (when supply curve = d_agg)
# 2.939244*q = 145996.9
# q = 49671.58


# Benefit to consumers under status quo is (39559.58)*(158034.280239-50000.)*(1/2) = 2136895376 for non-DAC
# Benefit to consumers under status quo is (10112)*(116854.835741-50000.02)*(1/2) = 338017948 for DAC 
# Aggregate benefit is 2,474,913,324
# Benefit to producers surplus under status quo is 1.2 bil
# Environmental cost = external cost amount times 49671.58
# 18,900 * 49671.58
```

```{r}
#Derive the optimal EV tax (in $ per vehicle) to internalize the lithium mining externality. Noting that recent research has shown that DACs are far more likely to contain mining activity, assume that the mining externality is borne entirely by the DAC group. What would be the effects of this tax on:
# (a) The amount of EVs produced and consumed (b) The price of EVs
# (c) Overall welfare of non-DAC consumers (d) Overall welfare of DAC consumers
# (e) EV producers
# (f) Total environmental damage
# (g) Total tax revenue generated

# New supply curve
# p = 1.006612*Q + 18,900

# a) Quantity of EVs will decrease
# b) 50000 + 18,900




```



6. 
```{r}
# Now, assume that all revenue from the EV tax will be redistributed to the consumers in proportion to their pre-tax consumption. For example, if 80% of the EVs were consumed by non-DAC consumers, then they get 80% of the tax revenue. Additionally, consider that emerging scientific evidence suggests the true environmental damages from lithium mining may be much higher than $300. For a range of values of external costs per kg of lithium ($350, $400, $450, and $500 per kg), calculate the effects of an EV tax on:1
# (a) Overall welfare of non-DAC consumers (b) Overall welfare of DAC consumers
# (c) EV producers 





```




